DELETE http://localhost:3000/carPost/deleteCarPost/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJzZWNvbmRfdXNlciIsImVtYWlsIjoidXNlcjJAbWFpbC5ydSIsImlzQWRtaW4iOmZhbHNlLCJleHAiOjE3NTk3OTc0MjV9.PWtoGV56dL_SaN7Zd4fTrmCoVjC1vBqPKiiuQ09a0Ao
Content-Type: application/json