DELETE http://localhost:3000/carPost/deleteCarPost/27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiIiLCJlbWFpbCI6ImNoZWxAbWFpbC5ydSIsImlzQWRtaW4iOnRydWUsImV4cCI6MTc2MDMwMzE1OH0.3TU9GnTFfwuiKuH5tetZmlD6fTI9wcgPqZZj1aVv4hA
Content-Type: application/json