POST http://localhost:3000/users/signUp
Content-Type: application/json

{
    "first_name": "Chel",
    "last_name": "Chel",
    "username": "chel-_-",
    "email": "chel@mail.ru",
    "phone_number": "5420221205",
    "password": "password"
}